name: Build - linux
on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: ./build_linux.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-linux
          path: ffmpeg/build
